### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.github.florent37.singledateandtimepicker.dialog.BaseDialog.isDisplaying()' on a null object reference

### ISSUE THREAD

**Issue by son2017** [florent37/SingleDateAndTimePicker#102]
when am add isDisplaying() method is showing null pointer exception .

**Comment by dreamsparkx** [comment]
'''Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference'''
This is what i am getting
