### ISSUE TITLE
Error:(615) duplicate value for resource 'attr/fontStyle' with config ''.

### ISSUE THREAD

**Issue by Dandriel** [florent37/SingleDateAndTimePicker#116]
After update my project to use "compileSdkVersion 26", i have next error:
.\.gradle\caches\transforms-1\files-1.1\singledateandtimepicker-1.2.2.aar\a7a30e790de9627246139381fc478852\res\values\values.xml
Error:(16, 5) error: duplicate value for resource 'attr/fontStyle' with config ''.
Error:(16, 5) error: resource previously defined here.

May be i'm making something wrong.  

Thank you.

**Comment by Dandriel** [comment]
Sorry about this.

**Comment by prajot-mobiefit** [comment]
hey even I m facing the same issue. Did you find any solution for it?
