### ISSUE TITLE
No way to close view on Main Activity onBackPressed(), or if user hits home

### ISSUE THREAD

**Issue by techartist** [florent37/SingleDateAndTimePicker#15]
I noticed this when trying to debug the app.  If I hit the back button or if my app crashes, the view stays on top with no way to close it.  I think it needs to be more tightly coupled with the activity so a call to onPause() or onDestroy will also close the window.

**Comment by nomanr** [comment]
You can handle the problem this way 

```
 @Override
    public void onBackPressed() {
        super.onBackPressed();
        if(dateAndTimePicker.isDisplaying())
            dateAndTimePicker.close();
        else
            super.onBackPressed();

    }
```
method `isDisplaying` is `isDiplaying` in current version, fixed the typo in #16
