### ISSUE TITLE
Please publish 2.0.6

### ISSUE THREAD

**Issue by khltrifork** [florent37/SingleDateAndTimePicker#157]
An extremely critical fix has been merged for 2.0.6, but 2.0.6 has not yet been released.
Over a month since last release, and over 2 weeks since the fix was merged.
https://github.com/florent37/SingleDateAndTimePicker/pull/152

Please publish 2.0.6, as without the fix, this library is not usable for anyone who tries to use it for apps below API 24, as they 100% guaranteed crash every single time

**Comment by florent37** [comment]
done ;) 
you have the 2.0.6 and 2.0.7

**Comment by Amr-Elmadah** [comment]
@florent37 That 2.0.6 version isn't shown in releases, why?
![image](https://user-images.githubusercontent.com/16728654/64122472-068fe380-cda2-11e9-940a-8645cf687ca6.png)
