### ISSUE TITLE
change button "Ok"

### ISSUE THREAD

**Issue by fajaranugrah** [florent37/SingleDateAndTimePicker#159]
Hello can i change button "Ok" to custom?
thank you

**Comment by fajaranugrah** [comment]
i mean like "Ok" to "Done"

**Comment by chandreshandroid** [comment]
See my answer.Hope you get this.
  
var b1=SingleDateAndTimePickerDialog.Builder(this).apply {


                bottomSheet()
                curved()
                displayMinutes(false)
                displayHours(false)
                displayDays(false)
                displayMonth(true)
                displayYears(true)
                displayDaysOfMonth(true)
                }
            






                  **b1.displayListener(object:SingleDateAndTimePickerDialog.DisplayListener{
                      override fun onDisplayed(picker: SingleDateAndTimePicker?) {
                       var view=   picker?.rootView
                          if(view!=null)
                          {
                              val buttonOk =
                                  view.findViewById(com.github.florent37.singledateandtimepicker.R.id.buttonOk) as TextView
                              buttonOk.text="Done"
                          }
                      }
                  })**
                 b1.listener { object :SingleDateAndTimePickerDialog.Listener{
                     override fun onDateSelected(date: Date?) {

                     }
                 } }

            b1.display()

**Comment by fajaranugrah** [comment]
@chandreshandroid thank you its work
