### ISSUE TITLE
WheelPicker java.lang.ArithmeticException divide by zero

### ISSUE THREAD

**Issue by fajaranugrah** [florent37/SingleDateAndTimePicker#193]
hello can help me what is this? and then how to fixed this

WheelPicker  java.lang.ArithmeticException 
divide by zero
com.github.florent37.singledateandtimepicker.widget.WheelPicker$1.run (WheelPicker.java:120)
android.os.Handler.handleCallback (Handler.java:789)
android.os.Handler.dispatchMessage (Handler.java:98)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6938)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:327)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1374)

i use this
implementation 'com.github.florent37:singledateandtimepicker:2.0.7'
thanks

**Comment by xsahil03x** [comment]
Update to 2.1.3

**Comment by fajaranugrah** [comment]
@xsahil03x okay i try update and then see again
thanks
