### ISSUE TITLE
Displaying a default date when opening

### ISSUE THREAD

**Issue by MaximilianKeppeler** [florent37/SingleDateAndTimePicker#22]

**Comment by deepwell** [comment]
I would like this as well. When the datepicker closes, no matter what date is selected when it's opened again it's reset to the current date and time. It should keep the date and time selected.

**Comment by Bhavdip** [comment]
@deepwell is right. There should be a method of set the date before open the date picker.

**Comment by florent37** [comment]
done, you can use `.defaultDate(date)`

**Comment by Bhavdip** [comment]
Thank you @florent37

**Comment by GordonHuangYong** [comment]
the "Hour" is always default hour.  no matter what hour you have selected.
@florent37

**Comment by GordonHuangYong** [comment]
as you can see. the 
![image](https://cloud.githubusercontent.com/assets/20039800/26239867/6c53bb9e-3cb1-11e7-81aa-4fb70bb66b91.png)

**Comment by ulaserdegor** [comment]
start and end default time may be different. 25.03.2019 00:00 and 25.03.2019 at 23:59. **defaultDate** method sets the same in two options. I think it needs updating.
