### ISSUE TITLE
Using SingleDateAndTimePicker as a NumberPicker

### ISSUE THREAD

**Issue by dimabran** [florent37/SingleDateAndTimePicker#223]
is it possible to use this library to create a numberpicker with the same design?

**Comment by momadthenomad** [comment]
I'm not sure what the author's response is, but I don't think this library should do that. Instead, since this library is open source, why don't you study it and use the ideas from this library to create a whole new library for a number picker library?

**Comment by florent37** [comment]
yes, to create this lib I forked an existing one, 
this lib usage is only for dates picker

btw you can use or fork the WheelPicker library to create a NumberPicker : 
https://github.com/AigeStudio/WheelPicker

(I think WheelPicker can just be used as it to hande your usecase)
