### ISSUE TITLE
Can't import it

### ISSUE THREAD

**Issue by Zeit42** [florent37/SingleDateAndTimePicker#258]
I placed 

`implementation 'com.github.florent37:SingleDateAndTimePicker:2.2.0'`

in my project level gradle dependencies, but when I hit sync, I get this error: 

`ERROR: Failed to resolve: com.github.florent37:SingleDateAndTimePicker:2.2.0`

**Comment by Kintanpatel4393** [comment]
Add Below line in your Project level Gradle,
 ```
allprojects {
    repositories {
        google()
        jcenter()
  //Add below Line
        maven { url "https://jitpack.io" }
    }
}
```
Downgrade SingleDateAndTimePicker Library,
`implementation 'com.github.florent37:SingleDateAndTimePicker:2.0.5'`

**Comment by xnxaxo** [comment]
@Zeit42 
implementation 'com.github.florent37:singledateandtimepicker:2.2.0'

readme update PR.
#260

**Comment by florent37** [comment]
fixed
