### ISSUE TITLE
Date picker not showing today and tomorrow day.

### ISSUE THREAD

**Issue by nasirlordno1** [florent37/SingleDateAndTimePicker#264]
Datepicker isnt showing today and tomorrrow date. and previous date dayname is also wrong. 
today date is 19 Mar.

![date-picker](https://user-images.githubusercontent.com/54404588/77055475-c23cfb80-69f2-11ea-957e-f8da6aa76a5b.jpg)

**Comment by fawadaliii** [comment]
i got same problem whats the issue is this?

**Comment by parkarta** [comment]
Yes this is the issue appearing my side too.. please help.

**Comment by fawadaliii** [comment]
@parkarta I also didn't find any solution till now.

**Comment by fawadaliii** [comment]
where is @nasirlordno1 any guide??

**Comment by nasirlordno1** [comment]
> where is @nasirlordno1 any guide??

no solution.I am also waiting for someone to answer.

**Comment by jturin** [comment]
Looks like the library is not prepared for leap years:
[https://github.com/florent37/SingleDateAndTimePicker/blob/master/singledateandtimepicker/src/main/java/com/github/florent37/singledateandtimepicker/widget/SingleDateAndTimeConstants.java#L9](url)

**Comment by ardevd** [comment]
Same issue here. Any way to resolve the issue?

**Comment by ardevd** [comment]
Downgrading to v2.1.4 fixes the issue for me.

**Comment by G00fY2** [comment]
Issue appears since 2.1.6. I am currently investigating and trying to provide a PR.

**Comment by arberg** [comment]
This issue can be closed now. Fixed in v2.2.1.
