### ISSUE TITLE
i think it's dependent on api 24.0.0

### ISSUE THREAD

**Issue by Alokvis53** [florent37/SingleDateAndTimePicker#27]
# first  of all thank you because your  project  help me alot to achieve few views, but my another experiment failed with below issue.
->experiments based on below detail
   ```
 compileSdkVersion 23
    buildToolsVersion "23.0.1"
`defaultConfig {
        applicationId "com.experiment.nu13"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }`
```
when i am integrating your dependency getting below error. 
Error:A problem occurred configuring project ':app'.
> Could not find appcompat-v7.jar (com.android.support:appcompat-v7:24.0.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/appcompat-v7/24.0.0/appcompat-v7-24.0.0.jar

any solution will be appreciated.

**Comment by florent37** [comment]
why not set your version to 24 ?
