### ISSUE TITLE
[BUG] Default time everything AM

### ISSUE THREAD

**Issue by Dozorov** [florent37/SingleDateAndTimePicker#29]
Fix this issue please.

**Comment by pragneshghoda** [comment]
Also Happens with me.

**Comment by pragneshghoda** [comment]
@florent37  Hello,

Can you please check for this issue ?

When I set **setMustBeOnFuture(true)**, it only sets date on future but we can select past time of this date. 

And if we set **setMinDate(new Date(System.currentTimeMillis()));** we can select time in future, but in this case AM-PM is not working properly. 

By default it takes AM as current/Min time. So If its 3.15 PM we can select time till 3.15 AM.

I have used below code for setting future time. But still having issues with AM-PM. 
```
singleDateAndTimePicker = (SingleDateAndTimePicker) getView().findViewById(R.id.single_day_picker);
        singleDateAndTimePicker.setMustBeOnFuture(true);
        singleDateAndTimePicker.setIsAmPm(true);
        singleDateAndTimePicker.setMinDate(new Date(System.currentTimeMillis()));

```
Any help would be welcomed :+1:

**Comment by praneethrahul** [comment]
It might be late but, still it will surely help someone using this library. After going thru the code i figured out how to fix this issue.

In SingleDateAndTimePicker.java, change following (Line no: 71):

`isAmPm = !(DateFormat.is24HourFormat(context));`
to
`isAmPm = (DateFormat.is24HourFormat(context));`


In WheelMinutePicker.java, in menthod `findIndexOfMinute(int minute)` line no: 79: change the following:

 ```
if (minute < value) {
                return i - 1;
            }
```
              to

```
if (minute < value) {
                return i;
            }
```

Above code will show up current time on Picker or if current time(minutes) doesn't fall under multiple of 5, then it will show time(minutes) greater than current time.


In WheelPicker.java, in menthod `findIndexOfDate(Date date)` line no: 857: change the following:
 ```
if (formatItem.equals(object)) {
        return i;
      }
```
              to
```
 if (formatItem.equals(object)) {
                return i + 1;
            }
```

Above code will not let the user to select the time less than current time.

**Comment by jseparovic** [comment]
I'm using `defaultDate(Date)` and it sets correctly.
```
.defaultDate(new Date())
```
However, we should be able to set defaultDate for tab0 and tab1 in the double picker

**Comment by florent37** [comment]
you can use `tab0Date`and `tab1Date`
