### ISSUE TITLE
Doesnt Close when BackPressed

### ISSUE THREAD

**Issue by deepakbaliga** [florent37/SingleDateAndTimePicker#30]
`SingleDateAndTimePickerDialog` doesnt close when pressed back.

**Comment by Bhavdip** [comment]
@deepakbaliga You can use `close()` method

**Comment by deepakbaliga** [comment]
It will messup my activity and fragment lifecycle if I have to do it onBackPressed.

**Comment by ulaserdegor** [comment]
Same problem!
