### ISSUE TITLE
How to remove AM&PM and show in 24 hours formate.

### ISSUE THREAD

**Issue by malibaig41** [florent37/SingleDateAndTimePicker#37]
`<com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker
        android:id="@+id/single_day_time_picker"
        android:layout_width="wrap_content"
        android:layout_height="230dp"
        app:picker_curved="true"
        app:picker_cyclic="true"
        app:picker_mustBeOnFuture="true"
        app:picker_visibleItemCount="7" />`

` SingleDateAndTimePicker dateTimePicker = (SingleDateAndTimePicker) rootView.findViewById(R.id.single_day_time_picker);`

`  dateTimePicker.setIsAmPm(false);`

I have used setIsAmPm( ) but no luck.

I am using this in a dialogFragment.

![inquiredialog](https://cloud.githubusercontent.com/assets/21278326/23609974/7d7441ea-0292-11e7-8e31-3a99dc400264.png)

**Comment by praneethrahul** [comment]
Late answer but still it might help someone.
In SingleDateAndTimePicker.java, change 

`isAmPm = !(DateFormat.is24HourFormat(context));`
  to
`isAmPm = (DateFormat.is24HourFormat(context));` 
(Line no: 71)

This will solve the issue.
