### ISSUE TITLE
switch between AM/PM and 24

### ISSUE THREAD

**Issue by smedic** [florent37/SingleDateAndTimePicker#44]
I always see 24h format in datetime picker.

I see that in 1.0.1 there was an option for this, but on 1.1.0 there is none.

How to switch?

**Comment by Hesamedin** [comment]
I guess it switches based on your device time settings. I have two devices one its time has set to 24h and the other 12h. When I run the app, I can see AM/PM on second device while it is not there in the first device.

**Comment by florent37** [comment]
you can use `setIsAmPm`
