### ISSUE TITLE
I want to hide minute and hour

### ISSUE THREAD

**Issue by hasan5151** [florent37/SingleDateAndTimePicker#46]
I want to hide minute and hour

**Comment by florent37** [comment]
in the new version you can use `displayMinutes` and `displayHours`

**Comment by hasan5151** [comment]
app:picker_displayHours="false"
app:picker_displayMinutes="false" 

it display AM/PM near date

**Comment by hasan5151** [comment]
![image](https://cloud.githubusercontent.com/assets/17989735/25897485/e8dfd7c4-35a9-11e7-966f-ffb233e6f135.png)

**Comment by florent37** [comment]
mmmm i'll modify displayHours="false" to hide also am/pm

**Comment by florent37** [comment]
fixed on `1.1.3`
