### ISSUE TITLE
setIsAmPm(false) don't redraw user interface

### ISSUE THREAD

**Issue by Gvardia** [florent37/SingleDateAndTimePicker#48]
When i set IsAmPm to false it still is showing am/pm on the view. I was fixing this by reflection 
Class<?> clazz = mDateAndTimePicker.getClass();
        try {
            Method updatePickerMethod = clazz.getDeclaredMethod("updatePicker");
            Method updateViewsMethod  = clazz.getDeclaredMethod("updateViews");
            updatePickerMethod.setAccessible(true);
            updateViewsMethod.setAccessible(true);
            updatePickerMethod.invoke(mDateAndTimePicker, new Object[]{});
            updateViewsMethod.invoke(mDateAndTimePicker,  new Object[]{});
        } catch (NoSuchMethodException e) {
            Log.e("PickDateAndTimeFragment", "NoSuch=" + e.getMessage());
        } catch (IllegalAccessException e) {
            Log.e("PickDateAndTimeFragment", "IllegalAccess=" + e.getMessage());
        } catch (InvocationTargetException e) {
            Log.e("PickDateAndTimeFragment", "InvocationTarget = " + e.getMessage());
        }
It seems that you just forgot in 
    public void setIsAmPm(boolean isAmPm) {
        this.isAmPm = isAmPm;
        updateViews();
    }
 add updatePicker();  because  updateViews(); only is changed backgroundcolor 
    private void updateViews() {
        dtSelector.setBackgroundColor(selectorColor);
    }

**Comment by florent37** [comment]
done

**Comment by florent37** [comment]
will be on next release

**Comment by rajscet** [comment]
setIsAmPm(true)  not working if i hide days
