### ISSUE TITLE
Language / Format

### ISSUE THREAD

**Issue by Shrewd** [florent37/SingleDateAndTimePicker#49]
Is it possible to change the format of the displayed days? Like capitilizing and so on... Only show numbers, etc...

Also, "Today" string is missing in a lot of languages, I know it can be overriden by using 
<string name="picker_today">hoy</string> in strings.xml (btw this is spanish one) in case you want to include it.

**Comment by florent37** [comment]
To add translations you just have to send a pull request of strings.xml
like other language I added.

What do you mean with date format ?

**Comment by Shrewd** [comment]
Language sent via pull request.

I mean this : ![s](https://cloud.githubusercontent.com/assets/3142122/26287663/a97fbd8a-3e80-11e7-9595-b6439da0a4ae.PNG)
As you can see, week days and months do not start with capital leter. While your captures show it correctly.
(My Today is in capital because I wrote it that way)
So It would be nice to be able to customize that

**Comment by florent37** [comment]
I added your translation, and allow to add a custom day formatter

```
setDayFormatter(SimpleDateFormat)
```

**Comment by florent37** [comment]
v1.1.4

**Comment by Shrewd** [comment]
I'm sorry but It doesn't seem to work :(

**Comment by florent37** [comment]
ok will check
