### ISSUE TITLE
Able to customize colors

### ISSUE THREAD

**Issue by techartist** [florent37/SingleDateAndTimePicker#6]
Is there a way to customize the colors for the dialog?  Background, etc.

**Comment by florent37** [comment]
yep I will do this soon 👍

**Comment by florent37** [comment]
done in 1.0.1 ;)

**Comment by techartist** [comment]
Can you update the read me file or give an example on how to set the colors?

**Comment by florent37** [comment]
yes 

```java
new SingleDateAndTimePickerDialog.Builder(context)
           
            .backgroundColor(Color.BLACK)
            .mainColor(Color.GREEN)
            
            .minutesStep(15)
            .mustBeOnFuture()
            .title("Simple")
            
            .display();
```

**Comment by techartist** [comment]
Does this work on the DoubleDateTimePicker as well?  You've added a bunch of new features which are not reflected in the ReadMe.md file.
