### ISSUE TITLE
Can't select any date but current datetime

### ISSUE THREAD

**Issue by techartist** [florent37/SingleDateAndTimePicker#7]
When I try and select another date on the wheel, the selection always goes back today's date. Running Marshmellow on Samsung Note 5.

**Comment by techartist** [comment]
Actually, I looked at the code and the date picker does not allow you to pick dates in the past, which I need for my app.

**Comment by Shailevy** [comment]
I forked and added canBeOnPast() to the dialog builder.. you can peek and do the same where ever you need it or I can send you my aar if you need it

I wish the florent37 will add "mustBeOnPast()"

**Comment by RodrigoSosa95** [comment]
Add a pull request, to see if he accepts it.

**Comment by florent37** [comment]
hi, sorry I can't code this week, but yes if you send me a pull request I will merge it,
I forgot to change this piece of code before submit to jcenter

**Comment by florent37** [comment]
done in 1.0.1 ;)
