### ISSUE TITLE
Add restriction to selection range for Date and Time

### ISSUE THREAD

**Issue by jinalptl1993** [florent37/SingleDateAndTimePicker#9]
I want restriction on inputs for date and time. Like we can give lower and upper limit for time picker to restrict user to choose time within specific range only. And same for date.

Thanks..!

**Comment by techartist** [comment]
I would like to see this also.

**Comment by florent37** [comment]
ok I implement it ;)

**Comment by florent37** [comment]
done  on 1.0.2

```java
.minDateRange(minDate)
.maxDateRange(maxDate)
```

**Comment by jinalptl1993** [comment]
Thanks :)

**Comment by paramarthasaha96** [comment]
Can you change the padding so that it displays the current range only(not the past dates)
