### ISSUE TITLE
Doesn't work without listeners

### ISSUE THREAD

**Issue by martinvano** [florent37/SingleDateAndTimePicker#90]
Most of the code crashes when scrolling without listeners. Let me show you where the problem is:
```
@Override
    protected void onItemSelected(int position, Object item) {
        if (onMinuteSelectedListener != null) {
            onMinuteSelectedListener.onMinuteSelected(this, position, convertItemToMinute(item));
        }
    }

    @Override
    protected void onItemCurrentScroll(int position, Object item) {
        if (lastScrollPosition != position) {
            onMinuteSelectedListener.onMinuteCurrentScrolled(this, position, convertItemToMinute(item));
            if (lastScrollPosition == 11 && position == 0)
                if (onMinuteSelectedListener != null) {
                    onMinuteSelectedListener.onMinuteScrolledNewHour(this);
                }
            lastScrollPosition = position;
        }
    }
```

In the onItemSelected, you check whether onMinuteSelectedListener is set or not. In onItemCurrentScroll you don't (actually you do, but not everywhere). This doesn't only apply to WheelMinutePicker but any WheelPicker. 

I understand that normally. programmers would attach the listener but for a quick prototyping when you don't actually use selected values this doesn't work. 

PS: Tested against latest version 1.2.0

**Comment by florent37** [comment]
can you make a pull request for that ?
