### ISSUE TITLE
SingleDatePicker in xml file does not display days

### ISSUE THREAD

**Issue by Yegorisa** [florent37/SingleDateAndTimePicker#93]
Hello,

I have an issue with your singleDateAndTimePicker, it does not show **days** in **selector**. I tried to make property **displayDays** to **true** but it did not help. Could you please help me out?

![image](https://user-images.githubusercontent.com/21309131/30414707-73f54748-9957-11e7-8464-ece8e2dc6fc1.png)

Sincerely,

Egor

**Comment by Nomanghous** [comment]
Hello developers,
You people are awesome. Thanks a lot for such a great work. Keep it up.
I am facing the issue with days even if i have set app:picker_displayDays="true".  
![capture](https://user-images.githubusercontent.com/12783763/34321969-4be68156-e83d-11e7-88ba-ff8476e4301e.PNG)

Kindly let me know if this really is a bug or want me to do something else?
Thanks
